apiVersion: v1
kind: Service
metadata:
  name: telco-churn-api
  labels:
    app: telco-churn-api
spec:
  type: NodePort
  selector:
    app: telco-churn-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
      protocol: TCP
